<a href="https://colab.research.google.com/github/phunguyen-coder/retail-sales-dataset/blob/main/Retail_sales_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **2. Prepare The Data**

#### Transforming/organizing the data

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#### Nhap va kham pha du lieu

In [3]:
retaild_df = pd.read_excel('/content/Retail Sales Data Project.xlsx')

retaild_df.describe()

,Transaction ID,Date,Age,Quantity,Price per Unit,Total Amount
count,1000.000000,1000,1000.00000,1000.000000,1000.000000,1000.000000
mean,500.500000,2023-07-03 00:25:55.200000256,41.39200,2.514000,179.890000,456.000000
min,1.000000,2023-01-01 00:00:00,18.00000,1.000000,25.000000,25.000000
25%,250.750000,2023-04-08 00:00:00,29.00000,1.000000,30.000000,60.000000
50%,500.500000,2023-06-29 12:00:00,42.00000,3.000000,50.000000,135.000000
75%,750.250000,2023-10-04 00:00:00,53.00000,4.000000,300.000000,900.000000
max,1000.000000,2024-01-01 00:00:00,64.00000,4.000000,500.000000,2000.000000
std,288.819436,NaN,13.68143,1.132734,189.681356,559.997632

In [4]:
retaild_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   datetime64[ns]
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: datetime64[ns](1), int64(5), object(3)
memory usage: 70.4+ KB

In [7]:
retaild_df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [6]:
#Tong so row duplicate
retaild_df.duplicated().sum()

np.int64(0)

In [8]:
#Loai bo duplicate
retaild_df.drop_duplicates()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
...,...,...,...,...,...,...,...,...,...
995,996,2023-05-16,CUST996,Male,62,Clothing,1,50,50
996,997,2023-11-17,CUST997,Male,52,Beauty,3,30,90
997,998,2023-10-29,CUST998,Female,23,Beauty,4,25,100
998,999,2023-12-05,CUST999,Female,36,Electronics,3,50,150
999,1000,2023-04-12,CUST1000,Male,47,Electronics,4,30,120

In [9]:
# Loai bo khoang trang cua cac cot co dang text
retaild_df['Customer ID'] = retaild_df['Customer ID'].str.strip()
retaild_df['Gender'] = retaild_df['Gender'].str.strip()
retaild_df['Product Category'] = retaild_df['Product Category'].str.strip()

In [10]:
#Bo sung du lieu thieu bang mean va mode
retaild_df['Total Amount'] = retaild_df['Total Amount'].fillna(retaild_df['Total Amount'].mean())
retaild_df['Quantity'] = retaild_df['Quantity'].fillna(retaild_df['Quantity'].mode())
retaild_df['Price per Unit'] = retaild_df['Price per Unit'].fillna(retaild_df['Price per Unit'].mean())

# Loai bo du lieu thieu
text_columns = ['Customer ID', 'Gender', 'Product Category']
retaild_df = retaild_df.dropna(subset=text_columns, how="any")

In [11]:
#Thuc hien dong bo du lieu text
retaild_df["Gender"] = retaild_df["Gender"].str.title()
retaild_df["Product Category"] = retaild_df["Product Category"].str.title()
retaild_df["Customer ID"] = retaild_df["Customer ID"].str.upper()

In [12]:
retaild_df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100

In [13]:
#Thuc hien chuyen Date -> Datetime
retaild_df["Date"] = pd.to_datetime(retaild_df["Date"])

In [14]:
retaild_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   datetime64[ns]
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: datetime64[ns](1), int64(5), object(3)
memory usage: 70.4+ KB

In [15]:
# Tao cot phat sinh
retaild_df['year_month'] = retaild_df['Date'].dt.to_period('M')
retaild_df['month'] = retaild_df['Date'].dt.month_name()

bins = [0, 18, 35, 50, 65, 100]

labels = ['0-17', '18-34', '35-49', '50-64', '65+']

retaild_df['age_group'] = pd.cut(retaild_df['Age'], bins=bins, labels=labels, right=False)

In [16]:
retaild_df.head()

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount,year_month,month,age_group
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150,2023-11,November,18-34
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000,2023-02,February,18-34
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30,2023-01,January,50-64
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500,2023-05,May,35-49
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100,2023-05,May,18-34

### Lam viec voi cac outlier

In [17]:
q1 = retaild_df["Total Amount"].quantile(0.25)
q3 = retaild_df["Total Amount"].quantile(0.75)
iqr = q3 - q1

median = retaild_df["Total Amount"].median()

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

print("q1 " + str(q1))
print("q3 " + str(q3))
print("iqr " + str(iqr))
print("median " + str(median))
print("lower_bound " + str(lower_bound))
print("upper_bound " + str(upper_bound))
# Create the boxplot
# fig, ax = plt.subplots(figsize=(7, 8))
# bp = ax.boxplot(retaild_df["Total Amount"], patch_artist=True,
#                 boxprops=dict(facecolor='#DDEBF7', color='#1F4E78', linewidth=2),
#                 medianprops=dict(color='#C00000', linewidth=2.5),
#                 whiskerprops=dict(color='#1F4E78', linewidth=1.5),
#                 capprops=dict(color='#1F4E78', linewidth=1.5))

# Add labels for Q1, Q3, and Median on the right side
# ax.text(1.15, q1, f'$Q_1$ (25th Percentile) = {q1:.2f}', va='center', ha='left', color='#2E75B6', weight='bold', fontsize=11)
# ax.text(1.15, median, f'Median ($Q_2$) = {median:.2f}', va='center', ha='left', color='#C00000', weight='bold', fontsize=11)
# ax.text(1.15, q3, f'$Q_3$ (75th Percentile) = {q3:.2f}', va='center', ha='left', color='#2E75B6', weight='bold', fontsize=11)

# Highlight IQR on the left side of the box using an arrow indicator
# ax.annotate('', xy=(0.85, q1), xytext=(0.85, q3),
#             arrowprops=dict(arrowstyle='<->', color='#7030A0', lw=2.5))
# ax.text(0.82, (q1 + q3)/2, f'Interquartile Range\n(IQR) = $Q_3 - Q_1$\n= {iqr:.2f}',
#         va='center', ha='right', color='#7030A0', weight='bold', fontsize=11,
#         bbox=dict(boxstyle='round,pad=0.3', facecolor='#F2EBF7', edgecolor='#7030A0', alpha=0.5))

# Final visual formatting
# ax.set_xticklabels(['Sample Dataset'], fontsize=12, weight='bold')
# ax.set_ylabel('Values', fontsize=12, weight='bold')
# ax.set_title('Visualizing the Interquartile Range (IQR) on a Boxplot', fontsize=14, weight='bold', pad=15)
# ax.set_xlim(0.4, 1.6)
# ax.grid(axis='y', linestyle='--', alpha=0.5)

# plt.tight_layout()
# plt.savefig('boxplot_iqr.png', dpi=150)

q1 60.0
q3 900.0
iqr 840.0
median 135.0
lower_bound -1200.0
upper_bound 2160.0

In [19]:
# Loc outlier cho total amount
total_outliers_df = retaild_df[(retaild_df["Total Amount"] < lower_bound) | (retaild_df["Total Amount"] > upper_bound)]
print(total_outliers_df)

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount, year_month, month, age_group]
Index: []

In [23]:
q1 = retaild_df["Age"].quantile(0.25)
q3 = retaild_df["Age"].quantile(0.75)
IQR = q3 - q1

median = retaild_df["Age"].median()

lower_bound = q1 - 1.5 * IQR
upper_bound = q3 + 1.5 * IQR

print(f"q1 {q1}")
print(f"q3 {q3}")
print(f"IQR {IQR}")
print(f"median {median}")
print(f"lower_bound {lower_bound}")
print(f"upper_bound {upper_bound}")


# Create the boxplot
# fig, ax = plt.subplots(figsize=(7, 8))
# bp = ax.boxplot(retaild_df["Age"], patch_artist=True,
#                 boxprops=dict(facecolor='#DDEBF7', color='#1F4E78', linewidth=2),
#                 medianprops=dict(color='#C00000', linewidth=2.5),
#                 whiskerprops=dict(color='#1F4E78', linewidth=1.5),
#                 capprops=dict(color='#1F4E78', linewidth=1.5))

# Add labels for Q1, Q3, and Median on the right side
# ax.text(1.15, q1, f'$Q_1$ (25th Percentile) = {q1:.2f}', va='center', ha='left', color='#2E75B6', weight='bold', fontsize=11)
# ax.text(1.15, median, f'Median ($Q_2$) = {median:.2f}', va='center', ha='left', color='#C00000', weight='bold', fontsize=11)
# ax.text(1.15, q3, f'$Q_3$ (75th Percentile) = {q3:.2f}', va='center', ha='left', color='#2E75B6', weight='bold', fontsize=11)

# Highlight IQR on the left side of the box using an arrow indicator
# ax.annotate('', xy=(0.85, q1), xytext=(0.85, q3),
#             arrowprops=dict(arrowstyle='<->', color='#7030A0', lw=2.5))
# ax.text(0.82, (q1 + q3)/2, f'Interquartile Range\n(IQR) = $Q_3 - Q_1$\n= {iqr:.2f}',
#         va='center', ha='right', color='#7030A0', weight='bold', fontsize=11,
#         bbox=dict(boxstyle='round,pad=0.3', facecolor='#F2EBF7', edgecolor='#7030A0', alpha=0.5))

# Final visual formatting
# ax.set_xticklabels(['Sample Dataset'], fontsize=12, weight='bold')
# ax.set_ylabel('Values', fontsize=12, weight='bold')
# ax.set_title('Visualizing the Interquartile Range (IQR) on a Boxplot', fontsize=14, weight='bold', pad=15)
# ax.set_xlim(0.4, 1.6)
# ax.grid(axis='y', linestyle='--', alpha=0.5)

# plt.tight_layout()
# plt.savefig('boxplot_iqr.png', dpi=150)

q1 29.0
q3 53.0
IQR 24.0
median 42.0
lower_bound -7.0
upper_bound 89.0

In [24]:
# Loc outlier cho age
age_outliers_df = retaild_df[(retaild_df["Age"] < lower_bound) | (retaild_df["Age"] > upper_bound)]

print(age_outliers_df)

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount, year_month, month, age_group]
Index: []

In [25]:
q1 = retaild_df["Quantity"].quantile(0.25)
q3 = retaild_df["Quantity"].quantile(0.75)
iqr = q3 - q1

median = retaild_df["Quantity"].median()

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

print(f"q1 {q1}")
print(f"q3 {q3}")
print(f"iqr {iqr}")
print(f"median {median}")
print(f"lower_bound {lower_bound}")
print(f"upper_bound {upper_bound}")

# Create the boxplot
# fig, ax = plt.subplots(figsize=(7, 8))
# bp = ax.boxplot(retaild_df["Quantity"], patch_artist=True,
#                 boxprops=dict(facecolor='#DDEBF7', color='#1F4E78', linewidth=2),
#                 medianprops=dict(color='#C00000', linewidth=2.5),
#                 whiskerprops=dict(color='#1F4E78', linewidth=1.5),
#                 capprops=dict(color='#1F4E78', linewidth=1.5))

# # Add labels for Q1, Q3, and Median on the right side
# ax.text(1.15, q1, f'$Q_1$ (25th Percentile) = {q1:.2f}', va='center', ha='left', color='#2E75B6', weight='bold', fontsize=11)
# ax.text(1.15, median, f'Median ($Q_2$) = {median:.2f}', va='center', ha='left', color='#C00000', weight='bold', fontsize=11)
# ax.text(1.15, q3, f'$Q_3$ (75th Percentile) = {q3:.2f}', va='center', ha='left', color='#2E75B6', weight='bold', fontsize=11)

# # Highlight IQR on the left side of the box using an arrow indicator
# ax.annotate('', xy=(0.85, q1), xytext=(0.85, q3),
#             arrowprops=dict(arrowstyle='<->', color='#7030A0', lw=2.5))
# ax.text(0.82, (q1 + q3)/2, f'Interquartile Range\n(IQR) = $Q_3 - Q_1$\n= {iqr:.2f}',
#         va='center', ha='right', color='#7030A0', weight='bold', fontsize=11,
#         bbox=dict(boxstyle='round,pad=0.3', facecolor='#F2EBF7', edgecolor='#7030A0', alpha=0.5))

# # Final visual formatting
# ax.set_xticklabels(['Sample Dataset'], fontsize=12, weight='bold')
# ax.set_ylabel('Values', fontsize=12, weight='bold')
# ax.set_title('Visualizing the Interquartile Range (IQR) on a Boxplot', fontsize=14, weight='bold', pad=15)
# ax.set_xlim(0.4, 1.6)
# ax.grid(axis='y', linestyle='--', alpha=0.5)

# plt.tight_layout()
# plt.savefig('boxplot_iqr.png', dpi=150)

q1 1.0
q3 4.0
iqr 3.0
median 3.0
lower_bound -3.5
upper_bound 8.5

In [26]:
# Loc outlier cho Quantity
quantity_outliers_df = retaild_df[(retaild_df["Quantity"] < lower_bound) | (retaild_df["Quantity"] > upper_bound)]

print(quantity_outliers_df)

Empty DataFrame
Columns: [Transaction ID, Date, Customer ID, Gender, Age, Product Category, Quantity, Price per Unit, Total Amount, year_month, month, age_group]
Index: []

In [27]:
#Luu Clean data

retaild_df.to_csv("clean_data.csv", index=False)